"""empty message

Revision ID: 60021926ec18
Revises: 542f1417f247
Create Date: 2021-11-25 20:33:56.446167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60021926ec18'
down_revision = '542f1417f247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'status')
    # ### end Alembic commands ###
