"""empty message

Revision ID: 9b784533c9a4
Revises: ad995d11ec1a
Create Date: 2021-11-22 19:14:17.934473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b784533c9a4'
down_revision = 'ad995d11ec1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bedrooms', sa.Column('bedroom', sa.String(), nullable=True))
    op.drop_column('bedrooms', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bedrooms', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bedrooms', 'bedroom')
    # ### end Alembic commands ###
