"""empty message

Revision ID: adf3f3b391c8
Revises: 9b784533c9a4
Create Date: 2021-11-22 19:46:25.202701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf3f3b391c8'
down_revision = '9b784533c9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bedrooms', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('bedrooms', 'bedroom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bedrooms', sa.Column('bedroom', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bedrooms', 'name')
    # ### end Alembic commands ###
