"""empty message

Revision ID: e66b48d3392c
Revises: 0d6e8c1ebd30
Create Date: 2021-11-03 21:55:32.903391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66b48d3392c'
down_revision = '0d6e8c1ebd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('document', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enabled')
    op.drop_column('users', 'email')
    op.drop_column('users', 'document')
    # ### end Alembic commands ###
